### ISSUE TITLE
Untranslatable strings

### ISSUE THREAD

**Issue by TotalCaesar659** [ray-lothian/UserAgent-Switcher#101]
@ray-lothian There are some untranslatable strings: "Filter among ...", "A to Z" and "Z to A" in pop-up menu and "to generate minified version, press Shift key while pressing this button" in options menu.
![1](https://user-images.githubusercontent.com/14265316/94370303-decf9400-00f7-11eb-9c76-74ec4d8a70a6.png)
![2](https://user-images.githubusercontent.com/14265316/94370307-e4c57500-00f7-11eb-91ed-9dc9012e980f.png)

**Comment by ray-lothian** [comment]
To simplify the localization process, I added the project to https://www.transifex.com/block-site-and-more/useragent-switcher/

**Comment by TotalCaesar659** [comment]
Thanks, it's great idea!

**Comment by TotalCaesar659** [comment]
One more in the options:
![1](https://user-images.githubusercontent.com/14265316/94502411-be452e00-020c-11eb-8a7e-10819cb03182.png)

**Comment by ray-lothian** [comment]
done! @TotalCaesar659 please note that we need localized store listing content too; https://github.com/ray-lothian/UserAgent-Switcher/tree/master/store

**Comment by TotalCaesar659** [comment]
Thanks, https://github.com/ray-lothian/UserAgent-Switcher/pull/102 is updated.
