### ISSUE TITLE
can't login to google

### ISSUE THREAD

**Issue by UltraBlackLinux** [ray-lothian/UserAgent-Switcher#110]
Hey there,
so I tried to log into my google account, but it didn't work, and I found out, it was because of the user agent switcher...
Please try to fix this, thanks!

I am using Firefox nightly

**Comment by UltraBlackLinux** [comment]
*it sais it's unsafe*

**Comment by ray-lothian** [comment]
I am not able to reproduce. What are your OS, and browser? Also what is the UA string?

**Comment by UltraBlackLinux** [comment]
@ray-lothian default ua manjaro linux

**Comment by firepainting** [comment]
This also happens to me, first discovered when logging in on YouTube.

Just at the logging in part, though. After that I just enable back UA Switcher and everything's back to normal.

On Firefox Browser 86.0 (64-bit) on Linux Mint 20.1 Cinnamon.

Thank you.

**Comment by ray-lothian** [comment]
See https://github.com/ray-lothian/UserAgent-Switcher/issues/121
