### ISSUE TITLE
incorrect platform value returned for MacOS

### ISSUE THREAD

**Issue by practik** [ray-lothian/UserAgent-Switcher#112]
To reproduce:
1. On a computer running MacOS, run a baseline test at `coveryourtracks.eff.org` and check the result under Platform; it should be 'MacIntel'.
2. Now, using User Agent Switcher and Manager, choose a MacOS UA string and run the Cover Your Tracks test again.
Expected result: The platform value should be 'MacIntel' as before.
Actual result: The platform value is 'Mac OS'.

**Comment by ray-lothian** [comment]
I believe this is fixed by fixing #115. Please reopen if after the upcoming update the bug is yet not fixed.

**Comment by practik** [comment]
Hmm, I'm skeptical since at #115 you say it's a FF-only bug, and I noticed the problem on Vivaldi. But I'll look for the update and test it again then.
