### ISSUE TITLE
Black list is not working

### ISSUE THREAD

**Issue by liar666** [ray-lothian/UserAgent-Switcher#113]
Hi,

I have configured User Agent Switcher & Manager not to be active on a few websites, like M$ Teams, Zoom and WebEx, because these websites use the User Agent to determine your system and act accordingly (e.g. Zoom & M$ Teams propose to download a ".exe" if your UA is a M$ one or simply refuse to work if you do not have a M$ UA).

I'm almost sure it was working when I defined these restrictions (a few months back). Unfortunately, it does not work as for a few days/weeks...

Picture1: I've change the UA in general to Edge/Windows and Zoom website react according to this
![2020-12-11-151625_3840x1080_scrot](https://user-images.githubusercontent.com/3216927/101923470-b6701580-3bcf-11eb-8594-02aea0cd4bb9.png)

Picture2: BUT I have added `zoom.us` to the blacklist, so zoom should not use the UA I've set, but the actual one of the browser 
![2020-12-11-152229_3840x1080_scrot](https://user-images.githubusercontent.com/3216927/101923731-136bcb80-3bd0-11eb-9842-cae9fbf82677.png)

I'm on Linux Mint with FF 83.0 and latest UserAgent-Switcher  (from Mozilla repo).

**Comment by liar666** [comment]
Any news? It's totally blocking access to certain sites :[

**Comment by ray-lothian** [comment]
sorry for the delay. You need to add the "hostname" which is "univ....zoom.us"
