### ISSUE TITLE
Wrong UA in Private Mode

### ISSUE THREAD

**Issue by Hiche3** [ray-lothian/UserAgent-Switcher#114]
1) Enable addon to be used in Private Mode
2) While in non-private mode, change default User Agent to Firefox version 72, using the GUI.
3) Hover over the UA icon, which will say [Custom]...Firefox **72**
4) Open a new private window, and hover over the UA icon, which will now say [Custom]...Firefox **83** (or whatever your current version is).
5) Click test User Agent (non-private and private window), which will show the user agent as 72 and 83, respectively.

**Comment by ray-lothian** [comment]
Should have been fixed by https://github.com/ray-lothian/UserAgent-Switcher/commit/ae8219dd9e76c7623e17fb01ec80d115a1364a46. Note that most likely you will need to set a custom UA for the private mode in FF, since it is considered as a new container.
