### ISSUE TITLE
Issues on Facebook, Google, Twitter, Spotify

### ISSUE THREAD

**Issue by firepainting** [ray-lothian/UserAgent-Switcher#120]
Hi. Thank you for this add-on.

I'm using User-Agent Switcher and Manager Version 0.4.6 on Firefox 87.0 (64-bit) on Linux Mint 20.1 Cinnamon.

[Edit 1: User agent is "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.107 Safari/537.36"]

On Facebook I'm having two issues.
(1) Going to facebook.com I get "Your Request Couldn't be Processed. There was a problem with this request. We're working on getting it fixed as soon as we can."
(2) Some videos won't load.
Workaround: Include facebook.com in Disable Spoofing.

Cannot sign in on Google. "Couldn’t sign you in. This browser or app may not be secure. Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in."
Workaround: Include google.com in Disable Spoofing.

On Twitter the audio of videos is "in slow-mo."
Workaround: Disable add-on. Including twitter.com in Disable Spoofing does not work.

Going to open.spotify.com I get “Something went wrong. Try reloading the page.”
Workaround: Include spotify.com in Disable Spoofing--but doing this does not load images (album covers, artist avatars, etc.)--"Refresh Tab" must be clicked within the add-on's drop-down window.

Thank you.

**Comment by ray-lothian** [comment]
Same as https://github.com/ray-lothian/UserAgent-Switcher/issues/121

I guess we just need to add these login pages to the exception list. When you are logged in, you can change the UA back to what you needed.
