### ISSUE TITLE
Container support

### ISSUE THREAD

**Issue by neekt** [ray-lothian/UserAgent-Switcher#13]
Hi there, I was just wondering if you had considered making this extension compatible with Firefox's multi-account containers? E.g., spoofing the user agent on all sites visited while browsing in a particular container? I don't actually know if this is possible, but could be useful.

Thanks for maintaining a great extension, and sorry for cross-posting on add0n.com

**Comment by Dopebiz6Dime** [comment]
azure has a good storage container

**Comment by Dopebiz6Dime** [comment]
Azure

**Comment by JesterJinx** [comment]
Omg that'd be amazing.

**Comment by mbrav** [comment]
Honestly think this will unleash the full potential of the UserAgent-Switcher plugin. With recent versions of Firefox, multi-account container functionality has evolved significantly in the past 6 months. I personally already have almost all site cookies jailed in their separate containers while using helpful plugins like [Cookie Quick Manager](https://addons.mozilla.org/en-US/firefox/addon/cookie-quick-manager/) for inspection purposes, but if I were able to change my user-agent string on per container basis, that would really bring the potential of this plugin forward.
