### ISSUE TITLE
Minor difference between "custom" mode and "always on"

### ISSUE THREAD

**Issue by cdpuff** [ray-lothian/UserAgent-Switcher#15]
I'm using this excellent add-on to persuade Facebook to properly display videos inline in my Firefox 60/Linux Mint 18.3 installation.  It works very well for this purpose; I can get a nicely usable Facebook page if I pretend to be Safari on MacOS.   However:-

I put the relevant user-agent string into the JSON object and selected "custom" mode, and reset the top level user agent.  Now, Facebook mostly renders OK but there are subtle differences.  There's a scrolling box on replies to posts which makes it difficult to edit, and the layout of items on the top nav bar is fill-justified rather than centered.

Summary: Expect same behavior from domain defined in custom mode and "always on" mode, but see differences.

**Comment by ray-lothian** [comment]
can you reproduce this on Chrome too?
