### ISSUE TITLE
not complete spoof

### ISSUE THREAD

**Issue by Quantenzitrone** [ray-lothian/UserAgent-Switcher#158]
[This](https://webbrowsertools.com/useragent/) website has some tools to test your browsers privacy. So i found out, UserAgend-Switcher does not fully spoof the browsers user agent.
For example, if I select Safari 15.4 MacOS 10.15.7 with the user agent "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15" I get the correct results for "navigator.UserAgend" but the "iframe navigator.UserAgend" as well as "navigator.AppVersion" as well as "iframe navigator.AppVersion" still show the values for my actual browser, Firefox 100 on Linux.

As long as this is not fixed, I can recommend the extension [Chameleon](https://addons.mozilla.org/en-US/firefox/addon/chameleon-ext/) (Only for Firefox, but you should use Firefox for privacy reasons anyway). It has less User Agents to select from and has some more functionality, but at least it works correctly.

**Comment by r3a1d3a1** [comment]
That too is not perfect however. Check [this](https://github.com/sereneblue/chameleon/issues/533) out as an example.

**Comment by ray-lothian** [comment]
There is no bulletproof method to hide browser type. For instance, a website can detect your browser type with a simple CSS matching such as:
```js
CSS.supports('-moz-appearance', 'none')
```

This extension tries to protect the user as much as possible. For better protection, it is recommended to also use the `--user-agent` command-line switch.
