### ISSUE TITLE
Unable to type in Google Docs

### ISSUE THREAD

**Issue by SteelEyeballSac1** [ray-lothian/UserAgent-Switcher#165]
My default user-agent is <code>Mozilla/5.0 (X11; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0</code>. When I change to <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36</code>, I am unable to type in Google Docs.

**Comment by JeffOfTheSixPaths** [comment]
I had the same problem. You should be able to type if you reset your user agent.

**Comment by serniebanders** [comment]
I have this issue too.

**Comment by SteelEyeballSac1** [comment]
I found that by going to [about:config](about:config) and changing the value of `general.useragent.override` to something like `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0` I can avoid this issue. Still annoying though.
