### ISSUE TITLE
Google Admin Console Extension Policy

### ISSUE THREAD

**Issue by mackenziepsilb** [ray-lothian/UserAgent-Switcher#169]
I am looking to deploy this to our ChromeOS users and I'm trying to set a policy in our Chrome Admin console for the extension policy settings. I'm using the string below, but it doesn't appear to show up when I look at chrome://policy. Is it not possible to do this or do I have something wrong? 

{"json-forced":{"blacklist":[],"cache":true,"custom":{},"exactMatch":false,"faqs":true,"json-forced":false,"json-guid":"afbe6f83-3784-476f-8c74-319414487d3a","last-update":1669086859994,"log":false,"mode":"whitelist","parser":{},"popup-browser":"Chrome","popup-os":"Windows","popup-sort":"descending","protected":["google.com/recaptcha","gstatic.com/recaptcha","accounts.google.com","accounts.youtube.com","gitlab.com/users/sign_in"],"siblings":{},"ua":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36","whitelist":["ajax.aspnetcdn.com","appsforoffice.microsoft.com","browser.events.data.microsoft.com","browser.pipe.aria.microsoft.com","content.powerapps.com","fpc.msedge.net","outlook.office365.com","res.cdn.office.net","upload.fp.measure.office.com","silberlinemfg.crm.dynamics.com","outlook.office.comm","sharepoint.com"]}}

**Comment by mackenziepsilb** [comment]
I was able to set in the Google Admin console for the extension policy and it shows up in the Chrome policies but doesn't actually affect the options in the extension.


![image](https://user-images.githubusercontent.com/51678264/208804650-2b55bdc1-fc25-46cf-a435-0687b13bd3dd.png)


{
    "json": {
        "Value": "{\"blacklist\":[],\"cache\":true,\"custom\":{},\"exactMatch\":false,\"faqs\":true,\"json-forced\":false,\"json-guid\":\"d138f5f5-7afd-4db4-8758-0847724967e4\",\"last-update\":1669086859994,\"log\":false,\"mode\":\"whitelist\",\"parser\":{},\"popup-browser\":\"Chrome\",\"popup-os\":\"Windows\",\"popup-sort\":\"descending\",\"protected\":[\"google.com/recaptcha\",\"gstatic.com/recaptcha\",\"accounts.google.com\",\"accounts.youtube.com\",\"gitlab.com/users/sign_in\"],\"siblings\":{},\"ua\":\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36\",\"userAgentData\":true,\"whitelist\":[\"ajax.aspnetcdn.com\",\"appsforoffice.microsoft.com\",\"browser.events.data.microsoft.com\",\"browser.pipe.aria.microsoft.com\",\"content.powerapps.com\",\"fpc.msedge.net\",\"outlook.office365.com\",\"res.cdn.office.net\",\"upload.fp.measure.office.com\",\"silberlinemfg.crm.dynamics.com\",\"outlook.office.comm\",\"sharepoint.com\",\"live.com\"]}"
    }
}

**Comment by ray-lothian** [comment]
I just tried the JSON and it works for me. Have you restarted the extension?

<img width="722" alt="one" src="https://user-images.githubusercontent.com/29911230/209459233-8e7d90b0-1038-4755-91aa-d71250bb556b.png">
<img width="735" alt="two" src="https://user-images.githubusercontent.com/29911230/209459235-a32f85c9-1acf-4975-9b88-347a8cf6c6cb.png">

**Comment by mackenziepsilb** [comment]
Thanks it works now. By the way, for others that are trying to do this this encoder (http://raymondhill.net/ublock/adminSetting.html) helped to get this in the right format for the Google admin console.

**Comment by arizvisa** [comment]
Can this issue be closed, since it was resolved?
