### ISSUE TITLE
Google actually knows I'm spoofing the user agent

### ISSUE THREAD

**Issue by Kruegerrr** [ray-lothian/UserAgent-Switcher#177]
I'm using Firefox on a Linux PC and I wish I can spoof my OS as Windows. I have changed my user agent with this extension and I have also set `general.oscpu.override` to `Windows NT 10.0` and `general.platform.override` to `Win32` to match a Windows device. This can fool most websites that didn't apply subtle techniques for OS and platform detection. However, my OS is still recognized as Linux when I log in my Google account. Are there any things I can do to circumvent the more advanced analysis Google has applied?

**Comment by Iey4iej3** [comment]
It is probably related to "Disable Spoofing" setting. By default, it contains
```
google.com/recaptcha, gstatic.com/recaptcha, accounts.google.com, accounts.youtube.com, gitlab.com/users/sign_in
```
which should have something to do with google login.

**Comment by ianisfmi** [comment]
> 

Is this setting in Firefox or in the add-on? I have searched in about:config and I did not find a 'disable spoofing' setting in there.

**Comment by Iey4iej3** [comment]
It is in "Options" of this addon (if you do not see it, either your Firefox or your addon is probably not up-to-date).
