### ISSUE TITLE
option to have a fix user agent for one website and not one tab 

### ISSUE THREAD

**Issue by slayernominee** [ray-lothian/UserAgent-Switcher#181]
it would be nice to set a fix user agent for a specific website and only the website nothing more. because its troublesome to always reset the useragent after leaving the website

**Comment by ElementalWarrior** [comment]
You can define this in the options menu. For example setting

```
{
  "www.bing.com": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.26/8mqLqMuL-37"
}
```
Under custom mode in the options.
This lets you use their ai chat on firefox :D

**Comment by slayernominee** [comment]
thanks a lot, thats what I need and in my case this is sufficient.
but i think it would be a big help just for simplicity for many people to have a button in the popout where you can just click for this site and it will save the current user agent in the custom list

**Comment by slayernominee** [comment]
and if the custom mode is active it would be helpful to have an option to use the settings in the popout just for any other site

**Comment by arizvisa** [comment]
can this issue be closed since the original problem was resolved?
