### ISSUE TITLE
Vulnerability: Cross-Site Scripting

### ISSUE THREAD

**Issue by websecnl** [ray-lothian/UserAgent-Switcher#19]
by changing user agent to: '); alert('1
it will alert '1' on every tab.

**Comment by ray-lothian** [comment]
Is this something we need to worry about? A user manually enters something which is not valid. No website can write to the protected storage

**Comment by websecnl** [comment]
@ray-lothian nope, just while pentesting i tought for a moment i found an Self-XSS vulnerability ... but it seemd to affect the piece of JS code of the user agent switcher.

it only coused some confusion for moment, but its nothing critical.

**Comment by ray-lothian** [comment]
All good then
