### ISSUE TITLE
Possiblity to overwrite user-agent per domain

### ISSUE THREAD

**Issue by grimpy** [ray-lothian/UserAgent-Switcher#2]
I dont want to overwrite my user-agent on all websites. But some websites falsely claim firefox is not supported (or not well supported) It would be nice to select an user-agent per domain for such websites

**Comment by GUiHKX** [comment]
+1

**Comment by Gitoffthelawn** [comment]
This can be accomplished via selecting the white-list and custom modes in the settings UI.

**Comment by ray-lothian** [comment]
True, I wasn't getting GitHub emails! So I guess we can close this one.

**Comment by Gitoffthelawn** [comment]
@ray-lothian What do you think of the idea proposed by @anewuser to apply the UA change to multiple hosts for a domain?

**Comment by ray-lothian** [comment]
We now have exact matching option in the options page. If it is unchecked and `slashdot.org` is in the list, then `m.slashdot.org` matches as well.
