### ISSUE TITLE
Feature Request：Load custom mode by remote URL

### ISSUE THREAD

**Issue by whymesay** [ray-lothian/UserAgent-Switcher#217]
When there are multiple browsers and each plugin needs to be changed, can a remote URL be loaded in custom mode to achieve unified configuration across multiple browsers

**Comment by ray-lothian** [comment]
This extension supports managed storage. You can follow the browser spec to configure it. 

https://webextension.org/listing/useragent-switcher.html#faq20

**Comment by whymesay** [comment]
@ray-lothian 
I have many machines, like a browser cluster, they are not on the local network

**Comment by ray-lothian** [comment]
I see, the next release will support updating preferences from a remote server. You can download the "v3" version and give it a try on Chrome.

**Comment by whymesay** [comment]
That's cool  !  thanks .

**Comment by cheng4kn** [comment]
> the next release will support updating preferences from a remote server. You can download the "v3" version and give it a try on Chrome.

When to release the LTS of V3? And I wanna use it too, thanks.

**Comment by whymesay** [comment]
@ray-lothian I have installed the v3 version plugin. There are some bugs here. when I save settings multiple times, plugin don't request remote url again.So it's not possible to trigger subsequent updates.this is my conf file ：https://raw.githubusercontent.com/whymesay/cdn/main/UserAgent-Switcher/configuration.json . And may it be automatically updated after setting the remote address?

**Comment by ray-lothian** [comment]
> When to release the LTS of V3? And I wanna use it too, thanks.

Probably in a few days on Chrome Webstore first.

**Comment by ray-lothian** [comment]
> when I save settings multiple times, plugin don't request remote url again

The extension only read remote JSON once per startup. So you need to restart the extension on developer mode or restart the browser.

Also if the URL changes, it reads the JSON once more.
