### ISSUE TITLE
uasw-json-data cookie

### ISSUE THREAD

**Issue by rezmus** [ray-lothian/UserAgent-Switcher#219]
how to prevent uasw-json-data cookie being sent to sites when user agent is being spoofed?

after site responses with Location header, all future requests (get/post) have uasw-json-data cookie with jsonify ua data.

**Comment by ray-lothian** [comment]
Can you give an example? The extension only adds `uasw-json-data` to the main frame's response header to retrieve its data synchronously (no data is sent to the server at this point). This data is erased when the extension's JavaScript loads. I don't receive the data for other requests. In your situation, the extension either fails to delete the data or the content script is not loading correctly. What are your browser and OS?

**Comment by rezmus** [comment]
i'm on old machine with windows7/chrome109. extension used to work fine before for months. i started to see uasw-json-data since about a week. even created new fresh chrome profile with only this extension, but same story. i saw that uasw-json-data cookie is usually started to be sent when site does location redirect, after that all requests to this site have this cookie.

it happens on all sites, for example https://jestesmynatywbiedronce.pl

as soon as i fill date for example 1/1/2000 and hit the button i got this

![image](https://github.com/user-attachments/assets/3e531d65-752f-4da1-a749-10b567b4cc79)

**Comment by ray-lothian** [comment]
This one is the main response. Do you get the `uasw-json-data` on other requests too?

**Comment by rezmus** [comment]
when it starts to show up for current domain (usually after location redirection) it is present for all get/post requests for such domain including assets like css/img/js.

**Comment by ray-lothian** [comment]
The next release does not use `cookie` anymore. Should fix your issue.

**Comment by rezmus** [comment]
works fine now tx!
