### ISSUE TITLE
bug: update from remote server not work

### ISSUE THREAD

**Issue by whymesay** [ray-lothian/UserAgent-Switcher#227]
It only takes effect for the first time and cannot be updated after saving

**Comment by ray-lothian** [comment]
It only checks for updates after browser start or after the remote address is being updated.

https://github.com/ray-lothian/UserAgent-Switcher/blob/master/v3/managed.js#L49

**Comment by whymesay** [comment]
> It only checks for updates after browser start or after the remote address is being updated.-----------谷歌翻译-----------它仅在浏览器启动后或更新远程地址后检查更新。
> 
> https://github.com/ray-lothian/UserAgent-Switcher/blob/master/v3/managed.js#L49

remote address update?  Even if there are changes in remote content transmission, it will not be updated？

**Comment by whymesay** [comment]
I have changed the remote content, but the address has not changed. However, whether I restart or manually click update from remote server, it will not change. Only click reset to save again

**Comment by ray-lothian** [comment]
did you changed `json-guid`?
https://github.com/ray-lothian/UserAgent-Switcher/blob/master/v3/managed.js#L6

**Comment by whymesay** [comment]
> Did you change `json-guid`? https://github.com/ray-lothian/UserAgent-Switcher/blob/master/v3/managed.js#L6-----------谷歌翻译-----------您更改了 json-guid 吗？

no,I changed guid, it's working now
