### ISSUE TITLE
Add a quick toggle to enable/disable custom mode

### ISSUE THREAD

**Issue by BobVul** [ray-lothian/UserAgent-Switcher#23]
Custom mode is great for defining site-specific user agents, but sometimes I want it off for a specific instance. Currently, this means I need to go and disable the entire extension. It would be great if one of the following were possible:

* Add a button in the popup menu to temporarily override custom mode for one tab (or one window?).
* Add a quick toggle button in the popup menu to globally disable custom mode.

**Comment by ray-lothian** [comment]
You will be able to change modes from right-click context menu over the toolbar button;
![screen shot 2018-11-04 at 10 55 39 am](https://user-images.githubusercontent.com/29911230/47962675-64d42480-e020-11e8-88f1-f438a9de3335.png)

**Comment by BobVul** [comment]
Thanks, that looks great!
