### ISSUE TITLE
Sub-domains exact matching error

### ISSUE THREAD

**Issue by prowong** [ray-lothian/UserAgent-Switcher#27]
My setting is White-list mode : m.jd.com , and UA is Mozilla/5.0 (Android 7.0; Mobile; rv:61.0) Gecko/61.0 Firefox/61.0 
After upgrate to the version 0.26 , if  'Use exact matching' is unchecked, this URL https://item.jd.com/7341434.html will redirect to https://item.m.jd.com/product/7341434.html .It seems all sub-domains end with "m" like "item" match m.jd.com.   Is my setting wrong ?

**Comment by ray-lothian** [comment]
Thanks for the report. Please wait for the next update and report back.

**Comment by prowong** [comment]
Thank you.It's fixed.Thanks for your work.
