### ISSUE TITLE
Black list mode option does not work at all in Linux !

### ISSUE THREAD

**Issue by Nokia808** [ray-lothian/UserAgent-Switcher#29]
Hi. 1st, I would like to thank you for your very hard efforts to build such nice add-on !

However, it seem that your add-on has many bugs & need to fixing .....

One of the bugs is that the "black list mode" option does not working at all on Linux ! I'm on Linux Fedora X64 bit Cinnamon edition with Firefox 65.0 X64 bit. Your add-on version 0.2.6 come with setting at this mode by default with empty list. At this stage every thing is working okay (when black list is empty). But just if I add a hostname, then & save - while black list option still selected, your add-on then failed completely to change user agent at ALL sites & at ANY site !! I need to re-empty blacklist & save so as to remake add-on working again ! This mean that blacklist mode is currently useless !

Please your kind fix. The blacklist & whitelist features are the credentials of this add-on .....

**Comment by ray-lothian** [comment]
Thanks for the report. It should be fixed by the next release.

**Comment by Nokia808** [comment]
@ray-lothian 
Many thanks for your kind attention & fixes !
