### ISSUE TITLE
Icon in toolbar should refer to "set to default" instead to "disabled" when add-on set to default string

### ISSUE THREAD

**Issue by Nokia808** [ray-lothian/UserAgent-Switcher#30]
Hi. Currently with version 0.2.6 when user "reset" option it working very okay. But when mouse set to be over add-on icon in toolbar, then there will be windows will appear inside it written the following:

"UserAgent Switcher (disabled)" 

I suggest to change this to the following:

"UserAgent Switcher (set to default)"

This will be better to avoid confusion because add-on is really NOT disabled but in fact is setting to default string. 

Best.

**Comment by ray-lothian** [comment]
Thanks for the suggestion. Will be fixed on the next release.

**Comment by Nokia808** [comment]
Thank you for fixes !
