### ISSUE TITLE
Always show "Mozilla 5.0/" at begining of string ! Is this correct or it is shortage in add-on ?

### ISSUE THREAD

**Issue by Nokia808** [ray-lothian/UserAgent-Switcher#31]
Hi. I noticed that your applet always show "Mozilla" at start of any string I select EVEN IF IT IS NOT FIREFOX !!
Is this normal or it is a bug & shortage in add-on ?

For example: if I select "Chrome+Windows 10 OS .....", then it will show:

"Mozilla 5.0/.................................."

It seem to me that "Mozilla 5.0" should not appear & never detected by visited sites as currently the case, because this make visited site know that "Chrome+Windows" is a fake & it in fact is Firefox (being Mozilla) ..............

I'm on Fedora 28 X64 bit Cinnamon edition with Firefox 65.0 X64 bit.

Best.

**Comment by NoXPhasma** [comment]
This is correct, all browser agents start with Mozilla 5.0: http://useragentstring.com/pages/useragentstring.php

**Comment by kenyoni** [comment]
Actually, what it means is: 

Claims to be a Mozilla based user agent, which is only true for Gecko browsers like Firefox and Netscape. For all other user agents it means 'Mozilla-compatible'. In modern browsers, this is only used for historical reasons. It has no real meaning anymore. 

...cut and pasted from [here](http://useragentstring.com/)
