### ISSUE TITLE
Random user-agent string per hostname

### ISSUE THREAD

**Issue by pienisieni** [ray-lothian/UserAgent-Switcher#35]
I'd like to request support for a random user-agent string per hostname, not per page.

As far as I've experienced, if I set a group of random user-agent strings for a hostname, it will change randomly to a different one for every single page I open on that same website.

It's not very practical in terms of usability, actually browsing the website. So I'd like to have it set a random user-agent, which would stay for as long as I browse that website.

Great add-on btw. best user agent switcher there is for Mozilla.
Huge thanks for your consideration,
Chiappa

**Comment by ray-lothian** [comment]
Thanks for the suggestion. We will have this on 0.2.9 release. Basically you will need to add a new key to the JSON object that contains an array of hostnames to have per session fixed UA string. If you need this for all hostnames, add "*" to the list. Read more on FAQ 9; https://add0n.com/useragent-switcher.html
