### ISSUE TITLE
[Feature Request] More options for custom mode

### ISSUE THREAD

**Issue by tomas-chrastina** [ray-lothian/UserAgent-Switcher#48]
Hello!

it would be nice to have few more options in **Custom mode** like:
- Evaluate also all **ports** of host when there's not specific one defined. To be able to use
```
"site.com:1234": "<UserAgent1>"
"site.com": "<UserAgent2>"
```  
In current version rule `"site.com"` won't work for host `www.site.com:5678`.
- Add option to define **lists of hosts' (groups)** that should use the same user agent.

Thank you in advance for considering these.

--
Best regards,
Tomas.

**Comment by phantomsprawl** [comment]
TiA

**Comment by Grossdm** [comment]
@ray-lothian,

Please document this on the instruction website. I thought that this should be possible, but I had to look through closed Issues here on GitHub to find this.

You might consider allowing the GitHub wiki so that motivated users could help document the features.
