### ISSUE TITLE
[Bug] Incorrect UA in tooltip

### ISSUE THREAD

**Issue by tomas-chrastina** [ray-lothian/UserAgent-Switcher#49]
### Configuration
**OS:** Windows 7 x64 Pro
**Browser:** Firefox v68.0.2 (64-bit) (New profile w/ original settings and only this Extension installed)
**Extension mode:** Custom
```
{
    "www.google.com": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3835.0 Safari/537.36"
}
```

**Use caching:** Off

### Problem
On change of tab, icon tooltip is not displaying currently selected=correct UA. Icon look different=OK. Also UA in network requests is OK, Toolkip is not.

### Test
**OK**
**Site:** `https://www.google.com/`
**Network request:**
```
Host: www.google.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3835.0 Safari/537.36
```
![UA_OK](https://user-images.githubusercontent.com/14962885/64130744-95155c80-cdc4-11e9-8c28-3c0020279411.png)

**NotOK**
**Site:** `https://addons.mozilla.org/en-US/firefox/addon/user-agent-string-switcher/`
**Network request:**
```
Host: addons.mozilla.org
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
```
![UA_NotOK](https://user-images.githubusercontent.com/14962885/64130949-c5a9c600-cdc5-11e9-95ed-0a1e55126193.png)

Maybe tooltip is not refreshed when "Default UA" (not defined in JSON rules) is used?

**Comment by ray-lothian** [comment]
Thanks for the report. Should be fixed by https://github.com/ray-lothian/UserAgent-Switcher/commit/00909fa7b9da29b5f0e129354424fabae81c38ac. If not please reopen.
