### ISSUE TITLE
Add Gecko ID to manifest.json

### ISSUE THREAD

**Issue by TotalCaesar659** [ray-lothian/UserAgent-Switcher#51]
Hello @ray-lothian, could you add Gecko ID to manifest.json?
I wanted to add User-Agent Switcher to Firefox for automatic startup after new installing (https://support.mozilla.org/en-US/kb/deploying-firefox-with-extensions), but without this ID, I have to add it manually. It's not comfortable, unlike many other add-ons.

**Comment by ray-lothian** [comment]
Why manually? You just need to add the link of AMO page to the policies.json.

**Comment by TotalCaesar659** [comment]
"AMO page" for downloading from AMO? No, I meant I've downloaded XPI files to */distribution extensions/, and Firefox catches them when starting.
Anyway, thanks for advice, and please merge [this PR](https://github.com/ray-lothian/UserAgent-Switcher/pull/54) (I've found the ID in mozilla-recommendation.json in XPI file).

**Comment by ray-lothian** [comment]
See https://github.com/mozilla/policy-templates/blob/master/README.md

The id in the manifest causes issues with other browsers.

**Comment by TotalCaesar659** [comment]
OK, I'll close it then, ID that I've found works for now.
