### ISSUE TITLE
Auto advance browser version [Feature Request]

### ISSUE THREAD

**Issue by ivdimitro** [ray-lothian/UserAgent-Switcher#55]
My use case for the extension is to make Vivaldi look like Chrome because some sites are stupid enough to consider them different. 
I would like to be able to set an option "keep chrome version up to date" or "read Chrome version from the browser". Basically the user agent should present the Chrome version on which Vivaldi is based. 
I understand this might be a niche use case but can be nice to have it.

**Comment by ray-lothian** [comment]
Wait for the 0.3.4 release and follow https://add0n.com/useragent-switcher.html?version=0.3.4#faq18 to create a dynamic UA string.
