### ISSUE TITLE
Alias or keyword for browser default useragent for "*" (all hostnames) in custom mode?

### ISSUE THREAD

**Issue by zmni** [ray-lothian/UserAgent-Switcher#56]
Currently I have to specify the browser default useragent in full for "*". Is there a way I can use an alias or keyword as a reference to the browser default useragent? This is usefull so we don't have to update the string every new browser version update.

For example:

```json
{
    "*": "default",
    ...
}
```

`default` always expand to for example my current edge beta useragent: `Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.16 Safari/537.36 Edg/79.0.309.11`

**Comment by ray-lothian** [comment]
There is no need to set the "*" key. It is optional. If you have a user-agent string set from the browser popup, the extension is going to use it, otherwise, the default browser's user-agent string is used.
