### ISSUE TITLE
UserAgent-Switcher does not seem to work for later requests.

### ISSUE THREAD

**Issue by ndsvw** [ray-lothian/UserAgent-Switcher#58]
My goal is using the Chrome Browser but pretending to use the Firefox...

So I open the GitHub-page of this extension (https://github.com/ray-lothian/UserAgent-Switcher).
The request of the main site is done via the fake-user-agent (Firefox)... But all the later requests (for loading images, json files, js files, etc) seem to have the original user agent..

When I go to https://github.com/ray-lothian/UserAgent-Switcher and open the Developer tolls / Network and refresh the site, I can see all the sub-requests:
<img width="1177" alt="Bildschirmfoto 2019-11-18 um 23 59 10" src="https://user-images.githubusercontent.com/21332313/69101347-b1d63d80-0a5f-11ea-995b-3392c9068049.png">

If I choose the favicon-request for example, it tells me "Provisional headers are shown" and that the user agent is my real user agent:
<img width="1451" alt="Bildschirmfoto 2019-11-18 um 23 59 41" src="https://user-images.githubusercontent.com/21332313/69101374-c1ee1d00-0a5f-11ea-9716-f29b108fd927.png">

Is this a Chrome-related (Chrome is not able to handle faked user agents correctly) or does this extension not work (for me)?

**Comment by ray-lothian** [comment]
This request is a cached request. You cannot rely on what is shown for "Provisional headers"
