### ISSUE TITLE
Add LICENSE or COPYING file

### ISSUE THREAD

**Issue by Necklaces** [ray-lothian/UserAgent-Switcher#6]
Hi, @ray-lothian, great extension, thanks!

It's a little bit unclear what license this software goes under, though; projects on GitHub are not automatically "open source", in fact, any code or software without a license are copyrighted by its author by default.

I highly recommend choosing a license for this extension, or at least adding a copyright notice if you do not wish to make it FLOSS (free/libre, or open source - software).

Here's a nice website for choosing a license: https://choosealicense.com/

**Comment by inbasic** [comment]
Fixed! Thanks for the report.
