### ISSUE TITLE
Issues with cloudflare sites - Access denied based on browser signature

### ISSUE THREAD

**Issue by numericOverflow** [ray-lothian/UserAgent-Switcher#66]
I noticed that numerous sites utilizing cloudflare seem to reject connections from my browser when I have the addon enabled.  Simply disabling the "User-Agent Switcher and Manager" addon and refreshing the page gets around the issue.

I tried the "reset" feature in UASM, but that didn't fix the issue, I was still shown the cloudflare error page instead of my requested web page.  I'd expect that the default user agent should be sent in this case, and would not be suspicious to cloudflare.

I've attached a screenshot of the error I get, along with my exported config file for use replicating the issue.  I'm on Win10 with FF version 72.0.2 (64-bit).

[useragent-switcher-preferences.json.txt](https://github.com/ray-lothian/UserAgent-Switcher/files/4119419/useragent-switcher-preferences.json.txt)

![cloudflare_2020-01-27_145711x](https://user-images.githubusercontent.com/3429424/73215053-f5f95480-4118-11ea-8dfb-c4d83ae66152.jpg)

**Comment by ray-lothian** [comment]
Your global rule is not a valid UA string. Use something general such as "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0"
