### ISSUE TITLE
Feature suggestion: Automatically return latest version of Chrome

### ISSUE THREAD

**Issue by Mr-Personality** [ray-lothian/UserAgent-Switcher#69]
I've just installed your add-on and it seems great. I'm using it for privacy, so that my browser will show as the most popular browser and OS, making me less personally identifiable.

But for that to work, it will have to show the latest version of Chrome, since Chrome users will mostly have the latest version.

It seems like the only way to do this is for me to keep coming back to the add-on and switching to a recent User Agent with the latest Chrome. It would be great if the add-on could do this automatically!

To put it another way, the add-on's controls seem too complicated for me. I think it would be easier to use if you just had 4 options: OS, OS version, Browser, and Browser version - which is set to "always latest version" by default.

Another small thing while I'm here, I found the interface slightly confusing. At the bottom, there are boxes that say things like "Platform" and "Product". At first glance, these look like custom options, but actually they are purely information. This would perhaps be made clearer if they did not appear in white boxes, and perhaps if the text were gray, or even italicized. Just a thought.

I hope this feedback is helpful! :-)

**Comment by ray-lothian** [comment]
FAQ18? https://add0n.com/useragent-switcher.html

**Comment by ray-lothian** [comment]
please reopn if the FAQ18 is not what you are looking for.
