### ISSUE TITLE
Extension attempts to open a web page immediately + attempts to connect to a remote address when uninstalled

### ISSUE THREAD

**Issue by magicgoose** [ray-lothian/UserAgent-Switcher#7]
When I installed the extension, it immediately attempted to open a new tab with something like add0n.com/…
I did the only possible next step: immediately closed the tab and went to uninstall the extension.
When the extension was uninstalled, I noticed (in the system network monitor) that it tried to connect to the same host again. It looks suspicious.

**Comment by ray-lothian** [comment]
The FAQs page on the first install helps users to get themselves familiar with the extension. The uninstall page is helpful to get user feedback. You can review the add0n.com page to make sure it is a safe page.
