### ISSUE TITLE
User-Agent is not changed in websocket connection

### ISSUE THREAD

**Issue by giaptx** [ray-lothian/UserAgent-Switcher#80]
Thanks for a great extension.

When working with website support websocket. I see the user-agent is sent to websocket server is original UA.

You guys can have a test with https://www.websocket.org/echo.html

I'm using Chromium Version 80.0.3987.162

Thanks

**Comment by rayfoss** [comment]
confirmed... this is yet another place where the user agent leaks.

It's really hard to stop it from leaking... perhaps the best option is to just make a disclaimer about it. Is this method being abused in the wild?
