### ISSUE TITLE
Problem parsing JSON config for "custom mode"

### ISSUE THREAD

**Issue by dwaal** [ray-lothian/UserAgent-Switcher#85]
{
  "somedomain.com": "Mozilla/5.0 (Linux; Android 10; SM-G975U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.93 Mobile Safari/537.36",
  "someotherdomain.com": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0 Safari/605.1.15", 
}

In my tests, the last entry is ignored if I put a comma (see above) after the entry. The parser should handle this correctly with or without comma.

**Comment by ray-lothian** [comment]
The last entry cannot have ",". This is not a valid JSON. This extension uses `JSON.parse` method to validate.

**Comment by Korb** [comment]
@dwaal, jsonformatter.curiousconcept.com:
![2024-07-29_22-34-30](https://github.com/user-attachments/assets/158d884e-9f74-4883-82d6-03e2afdee7bc)
