### ISSUE TITLE
Add newest UA

### ISSUE THREAD

**Issue by foordeluxe** [ray-lothian/UserAgent-Switcher#87]
I wonder if it's possible to add the newest updated UA.
I found this [site](https://www.whatismybrowser.com/guides/the-latest-user-agent/) which have the most up to date UA.

**Comment by sionstar** [comment]
Is UA-Switcher still active and supported?

**Comment by ray-lothian** [comment]
I just pushed a new update to the list. @foordeluxe you can always prepare a JSON file containing new UAs, create a new list (e.g. list-10.json), and request a pull merge. See samples here; https://github.com/ray-lothian/UserAgent-Switcher/tree/master/node
