### ISSUE TITLE
User-agent list is empty upon install

### ISSUE THREAD

**Issue by scottdotjs** [ray-lothian/UserAgent-Switcher#89]
I've just installed on Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:80.0) Gecko/20100101 Firefox/80.0 and the user-agent list is completely empty.

![image](https://user-images.githubusercontent.com/32358661/89426976-a1bbd680-d732-11ea-9503-e7201e84bf0e.png)

**Comment by prafalski** [comment]
Same here. I think it's the today's update. I had it installed before and it worked like a charm, but today it's stopped. I've reinstalled the extension but no joy. Please help!
I'm using the latest Firefox on macOS.

**Comment by MissingUser** [comment]
Same problem here after update to 5 august version.
Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0

**Comment by GitHubUser071016** [comment]
Bugreport confirmed. Browser: Firefox 79.0

**Comment by foordeluxe** [comment]
I just saw this post. And now I'm not alone with the problem.
I use: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0

**Comment by ray-lothian** [comment]
PLease wait for the 0.4.0.1 release. This is FF on Windows issue which is hopefully fixed by https://github.com/ray-lothian/UserAgent-Switcher/commit/f792087171175d70f660aa9d400a67f3a9cb36f3

**Comment by eau-u4f** [comment]
same issue here, using firefox on linux, hopefully the update will fix this.
