### ISSUE TITLE
User-Agent Switcher, User-Agent Switcher and User-Agent Switcher

### ISSUE THREAD

**Issue by grahamperrin** [ray-lothian/UserAgent-Switcher#9]
![user agent switcher user agent switcher user-agent switcher user-agent switcher and user-agent switcher](https://user-images.githubusercontent.com/192271/35197274-e7d58852-fed4-11e7-9e94-b4bfd13280da.png)

Can you change the name of your User-Agent Switcher? To avoid confusion with the earlier User-Agent Switcher, which is still featured by Mozilla.

**Comment by ray-lothian** [comment]
We will be "User-Agent Switcher and Manager" then!
