### ISSUE TITLE
Can a group of websites share the same per-session random string (eg. Youtube.com, Youtu.be)?

### ISSUE THREAD

**Issue by kodwyp** [ray-lothian/UserAgent-Switcher#93]
Sorry, not sure if this is the place for support questions.  If not, please point me to the right direction.

First, thank you very much for all the work you are doing!  Clearly you have put a lot of work into this.

Is there a way to randomly pick one of several UserAgent strings, but have a group of websites use the same one?  In my case, since we know Google owns Youtube.com and Youtu.be, I'd like those three sites, "Google.com" and "Youtube.com" and "Youtu.be" randomly choose from several UserAgent strings, but then have the same string for all those three sites.

Otherwise, if **Youtu.be** uses "My 1st User Agent String" but **Youtube.com** uses "My 2nd User Agent String", then they can learn to associate those two and track.

Separate from this, thank you for putting the feature of `"_"` which tells the extension to stick with the same User Agent string for the entire session, and only change it in between browser sessions.  However, note that your FAQ page at https://add0n.com/useragent-switcher.html gives the wrong key, saying: 
	

> Note that as of version 0.2.9, the user can define an array with `““` key

I realized your example was inconsistent with the text, so I tried using `""` as the JSON key first.  When it didn't work, I tried the `"_"` key and it worked.

_Addendum: now trying to post this on GitHub using Markdown notation, I see that the underscore within the quotation marks was probably swallowed up by a similar markup processor.  Anyway, as it stands, there is no underscore in the explanation text which is misleading._

Also, your example only has one host, not a list.  For those of use unfamiliar with JSON and are not sure of the correct syntax for a list, I humbly suggest that you put a list as an example.  Instead of:
	`"_": ["www.example.com"]`
you might want to put:
	`"_": ["www.example1.com", "www.example2.com"]`
I figured it out eventually after doing web searches for JSON syntax, but it would be nice if the lowly script kiddies among us were able to just use your example out of the box.

Thanks again for all the work you are doing with this extension.  I realize that some people might say that those who are desperate enough to install an extension to avoid being tracked must have something to hide, but I think it's privacy is just a matter of human dignity, that we be able to close the door to our own home, and plug the cracks if we see people peeping through them.

**Comment by ray-lothian** [comment]
> I realized your example was inconsistent with the text

Thanks for the report. It is fixed now; https://add0n.com/useragent-switcher.html?tbr

> ..., I humbly suggest that you put a list as an example. Instead of:

Done!

> Is there a way to randomly pick one of several UserAgent strings, but have a group of websites use the same one?

As of the next release, there is a new box on the options page to keep this group. You can add all hostnames to the list, and the extension makes sure they all have a single user-agent string per session.
