### ISSUE TITLE
Buy Extension

### ISSUE THREAD

**Issue by ryanfishman90** [ray-lothian/UserAgent-Switcher#95]
Hello,
are you interested about to sell your UA Chrome Webstore extension? Can you please contact me via mail? lordsword88 @ gmail . com 

Thank you :)

**Comment by Pakbon** [comment]
Ray, did you or did you not sell your extension?
Given the below article, I'm forced to uninstall this extension until it's positively confirmed you still have control over this repo.
link:https://chris.partridge.tech/2020/extensions-the-next-generation-of-malware/help-for-users/

**Comment by numericOverflow** [comment]
I'm interested to know this as well.

**Comment by ray-lothian** [comment]
No, there is no plan for selling this extension. Don't worry.

**Comment by numericOverflow** [comment]
Great, thanks for the clarification!
