### ISSUE TITLE
How to get the "Consider Container" button back?

### ISSUE THREAD

**Issue by geniuszxy** [ray-lothian/UserAgent-Switcher#97]
I mis-click this button and it leaves a blank rectangle now. I've tried the "Reset" and "Restart" button but they have no effect.

![screenshot](https://user-images.githubusercontent.com/2471200/93705663-8cb7cd00-fb51-11ea-96a3-5df4855319ce.PNG)

**Comment by ray-lothian** [comment]
You need to remove the extension and reinstall it. The "Consider Container" grants new permission, and there is no way to undo unless you reinstall the extension.

**Comment by KrasnayaPloshchad** [comment]
This should be report to their Bugzilla.
